### ISSUE TITLE
Retry just test steps

### ISSUE THREAD

**Issue by jrpc12** [JoshKeegan/xRetry#112]
Is there is a way to retry the test steps instead to retry the whole scenario?

decorating the gherkin scenario with @retry when a step (given/when/then) fails, the retry start over from the beginning of the scenario and the behavior I want to provide is a way to retry the step that has failed only to do not run the steps that has already passed

**Comment by JoshKeegan** [comment]
Hi, this isn’t possible with this library. The custom logic that is applied is against the whole scenario, or test case for xunit. So it isn’t possible to retry just the failing step.

**Comment by jrpc12** [comment]
good to know @JoshKeegan I'll take a different approach to solve this requirement in my project
