### ISSUE TITLE
Log that test was retried

### ISSUE THREAD

**Issue by VladRatina** [JoshKeegan/xRetry#15]

**Comment by JoshKeegan** [comment]
This is actually already implemented, just not documented :)
We log this information to the XUnit diagnostic log, so to get access to this information you simply need to enable those logs for your test project.

To do so see the xunit docs at https://xunit.net/docs/configuration-files and set up an `xunit.runner.json` file with the following content:
```json
{
  "$schema": "https://xunit.net/schema/current/xunit.runner.schema.json",
  "diagnosticMessages": true
}
```

**Comment by JoshKeegan** [comment]
I've updated the docs to have a section on this (https://github.com/JoshKeegan/xRetry#viewing-retry-logs).
And the UnitTests project in the repo has also been set up to have these diagnostic logs, so that can be used as an example.
