### ISSUE TITLE
Request for strong named assembly 

### ISSUE THREAD

**Issue by joelverhagen** [JoshKeegan/xRetry#165]
Thanks for the library. I was wondering if it is possible for this to be released as a strong-named assembly. I currently encounter this when using xRetry in a strong named, .NET Framework test assembly:

`
System.IO.FileLoadException: Could not load file or assembly 'xRetry, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
`

The workaround is simple. Don't strong name your test assembly. Unfortunately, this does not work for `[InternalsVisibleTo]` friend assembly definitions (as far as I know).

I will attempt strong naming the project myself with a copy of the source code, to work around the problem.

**Comment by JoshKeegan** [comment]
Hi, your request is perfectly timed! The next version of xRetry will be strongly named & if you would like try try the v1.9.0-alpha package from nuget, it has this now.
Let me know if you have any issues with it.

**Comment by joelverhagen** [comment]
It's a Christmas miracle! 🎅

**Comment by joelverhagen** [comment]
It worked great. I'll close this issue since I am unblocked.

**Comment by JoshKeegan** [comment]
@joelverhagen v1.9.0 (non pre-release) is now out.
