### ISSUE TITLE
@retry does not work with Scenario Outline

### ISSUE THREAD

**Issue by kkdattaGIT** [JoshKeegan/xRetry#21]
If I add @retry for a Scenario Outline, we get
1. it would only discover 1 test even when there are multiple "Examples"
2. When the test is executed, we get {Test name} has multiple [Fact]-derived attributes

i.e:
@retry
Scenario Outline: COE Oversight User view State 11 And Select <NextState>
Given I call API <SubmissionState> for a user X
Then The Current State is <NextState>
Examples: 
| SubmissionState | NextState | 
| State1     | StateX     |
| State2     | StateY     |

**Comment by JoshKeegan** [comment]
`@retry` isn't yet implemented for scenario outlines. I've recently added xunit `[Theory]` support though which is needed for this. So I'll make Scenario Outline support next on the TODO list :)

**Comment by kkdattaGIT** [comment]
> `@retry` isn't yet implemented for scenario outlines. I've recently added xunit `[Theory]` support though which is needed for this. So I'll make Scenario Outline support next on the TODO list :)

Thanks for looking into it!!

**Comment by JoshKeegan** [comment]
This is now available in v0.5.0, which I've just published on nuget.
Let me know how you get on with it :)

**Comment by kkdattaGIT** [comment]
Thanks Josh. Worked like charm. Many thanks for your help.
