### ISSUE TITLE
Reqnroll support

### ISSUE THREAD

**Issue by edmolko** [JoshKeegan/xRetry#239]
We're planning to migrate from Specflow to Reqnroll due to the current state of the Specflow roadmap - inexistent.
Are you planning to create an xRetry.Reqnoll package?

**Comment by JoshKeegan** [comment]
Hi! Yes, I've been watching Reqnroll and would like to support it in xRetry. No work has started on it yet though.

**Comment by edmolko** [comment]
I'd imagine that it will be very similar to xRetry.Specflow since, for what it seems to me, Reqnroll is quite compatible with Specflow except for different namespaces.
I wouldn't mind to submit a Merge Request though, but I'm not sure if you prefer to refactor and create a shared project since a lot of xRetry.Specflow code will be similar and reused by xRetry.Reqnroll.

**Comment by JoshKeegan** [comment]
Started work on this in the [reqnroll branch](https://github.com/JoshKeegan/xRetry/tree/reqnroll). Went with a copy/paste, as even if there's some re-use, SpecFlow & Reqnroll will likely drift over time as Reqnroll gets developed.

Main things still to do:
- [ ] Check Reqnroll .Net framework version (if supported at all). For SpecFlow 4 they were targeting 4.6.2 IIRC
- [ ] Check Reqnroll dotnet version
- [ ] Extract common logic (e.g. `SkipException`, `Parsers`)?
- [ ] Re-design versioning & release process. Don't want to have to re-release xRetry and xRetry.SpecFlow, so each project should be able to be versioned & released independently. Ideally CI should integrate against the targeted version of xRetry from nuget too, not just the local code :thinking: 
- [ ] Alpha build & release so it can be tried in another project

**Comment by Drew99Kt** [comment]
any more updates on this? 

looks like SpecFlow is being abandoned with the last update 7 months ago, and no support for .8.  If this is uploaded to nuget ill be sure to to give it a try and report any issues.  Appreciate the work.

**Comment by JoshKeegan** [comment]
No new updates, I haven't had time to work on this since I last posted.

Most of what I have left are just "nice to have" changes, so if I don't get time to do all of them in the next few weeks I'll release an alpha build without them.

**Comment by stephendobro** [comment]
I am looking to try your alpha build as soon as it is available.

**Comment by JoshKeegan** [comment]
And it's released! 

Release notes: https://github.com/JoshKeegan/xRetry/releases/tag/xRetry.Reqnroll_v1.0.0
Nuget package: https://www.nuget.org/packages/xRetry.Reqnroll

Give it a go, and let me know if you have any problems :crossed_fingers: If there are problems, please report each as a new issue.
