### ISSUE TITLE
Reqnroll 2.1.0

### ISSUE THREAD

**Issue by JoshKeegan** [JoshKeegan/xRetry#250]
The plugin does work against this, but when I update locally CI fails. 

Error:
```log
CSC : error CS1705: Assembly 'Reqnroll.Generator' with identity 'Reqnroll.Generator, Version=2.0.0.0, Culture=neutral, PublicKeyToken=611ce36403091019' uses 'System.CodeDom, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' which has a higher version than referenced assembly 'System.CodeDom' with identity 'System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' [/src/src/xRetry.Reqnroll/xRetry.Reqnroll.csproj]
```

Expect the dotnet-mixed-build docker image needs updating with the latest version of mono.

**Comment by chrisbillson** [comment]
Think this is probably related to this: https://github.com/reqnroll/Reqnroll/issues/244

Looks like it should probably be fixed in the next version.

**Comment by JoshKeegan** [comment]
Thanks @chrisbillson, upgrading to Reqnroll 2.1.1 has fixed this :+1:
